### ISSUE TITLE
Thread kill feedback loop

### ISSUE THREAD

**Issue by mitchellwrosen** [nikita-volkov/slave-thread#11]
There's a feedback loop in thread destruction that goes like this:

- Thread 1 spawns thread 2
- Thread 2 crashes (propagating this to thread 1)
- Thread 2 begins tearing down its children
- Meanwhile, thread 1 begins tearing down _its_ children (including thread 2)
- Thread 2 crashes with `ThreadKilled` from thread 1 while tearing down its children, and throws this back to thread 1
- Thread 1 receives its own `ThreadKilled` from thread 2 while tearing down its other children, etc...

This can cause ghost threads (e.g. if thread 2 did not get around to killing its other children before thread 1 killed it).

I think distinguishing exceptions thrown from `slave -> master` as in #8 would be a good first step at solving this.

What are your thoughts? Thanks :)

**Comment by mitchellwrosen** [comment]
(A related question, which I could move to a new ticket, is does "hierarchical" finalization mean a thread's children are finalized before its _parent_, or before its _parent and any of its uncles_? Because currently, uncles are killed and finalized concurrently with children).

**Comment by nikita-volkov** [comment]
Damn it. This must be caused by the changes that we've recently introduced. I'll look into it.

> does "hierarchical" finalization mean a thread's children are finalized before its parent, or before its parent and any of its uncles?

It's supposed to be that children get finalized strictly before parents.

**Comment by nikita-volkov** [comment]
> I think distinguishing exceptions thrown from slave -> master as in #8 would be a good first step at solving this.

I feel like this bug should be solved without that.

**Comment by nikita-volkov** [comment]
I wonder how to reproduce this... Can you PR this as a test case?

**Comment by nikita-volkov** [comment]
One option to solve this that I see is to make the slave first kill its children and run its finalizer before rethrowing the errors to the parent. What do you think?

**Comment by mitchellwrosen** [comment]
> I feel like this bug should be solved without that.

Just to clarify, are you against that change?

> Can you PR this as a test case?

Absolutely.

> One option to solve this that I see is to make the slave first kill its children and run its finalizer before rethrowing the errors to the parent.

I like that change for two reasons - one, it may squash this bug (I'd have to think about it), and two, the teardown seems cleaner and less chaotic visually (that children are torn down before parent and all uncles)

**Comment by nikita-volkov** [comment]
Alright! It's fixed now. Thanks for the test!

>> One option to solve this that I see is to make the slave first kill its children and run its finalizer before rethrowing the errors to the parent.

> I like that change for two reasons - one, it may squash this bug (I'd have to think about it), and two, the teardown seems cleaner and less chaotic visually (that children are torn down before parent and all uncles)

I do like this too. However I've managed to fix without changing the semantics. Tell you what. Let's see how this goes for now and reserve that idea for later.

> > I feel like this bug should be solved without that.

> Just to clarify, are you against that change?

No. I'm still considering that PR. It's just that it seems that these issues can be viewed in isolation.

**Comment by mitchellwrosen** [comment]
Thank you for the fix!

**Comment by nikita-volkov** [comment]
I'm struggling to understand the test here. The fix for #13, which is on the fix-13 branch, fails on this test. Can you take a look at this?

**Comment by mitchellwrosen** [comment]
I've taken a look. The test actually, as written, doesn't make much sense anymore, but it did uncover a different bug! I'll annotate the code and send a PR.

**Comment by nikita-volkov** [comment]
LOL :) Man this stuff is fragile!
