### ISSUE TITLE
Thread is not guaranteed to kill slaves

### ISSUE THREAD

**Issue by mitchellwrosen** [nikita-volkov/slave-thread#13]
In `1.0.2.6`, a thread is not guaranteed to kill its slaves. For example:

- Thread 1 spawns threads 2, 3, 4
- Thread 1 ends, begins killing slave 2
- Meanwhile, thread 1 is killed, so slaves 3 and 4 are never killed

I've created a test that demonstrates this, PR incoming...

**Comment by nikita-volkov** [comment]
Are you certain the test in #14  is correct? Because I've sprinkled traces all over the place in my attempt to fix (which you can find on [branch fix-13](https://github.com/nikita-volkov/slave-thread/tree/fix-13)), and the traces indicate that everything is fine in the thread life-cycle. They all get to termination, however the test hangs forever.

Here's the output:
```
mojojojo:slave-thread mojojojo$ dist/build/test/test -p "Master kills all slaves"
ThreadId 5: Forking from ThreadId 4
All
  Master kills all slaves, even if it is thrown an exception during (#13): ThreadId 6: Forking from ThreadId 5
ThreadId 6: []
ThreadId 6: Finalizing
ThreadId 6: Waiting at registration gate
ThreadId 6: Deleting itself from the registry
ThreadId 6: Processing the exceptions
ThreadId 6: Processing the computation exception
ThreadId 6: Processing the slaves dying exceptions
ThreadId 6: Processing the finalizer exceptions
ThreadId 6: Finishing
ThreadId 5: [thread killed]
ThreadId 5: Finalizing
ThreadId 5: Waiting at registration gate
ThreadId 5: Deleting itself from the registry
ThreadId 5: Processing the exceptions
ThreadId 5: Processing the computation exception
ThreadId 5: Processing the slaves dying exceptions
ThreadId 5: Processing the finalizer exceptions
ThreadId 5: Finishing
^C
```

**Comment by mitchellwrosen** [comment]
Interesting, the test is relying on GHC delivering `BlockedIndefinitelyOnMVar`, which I wasn't sure about. I'll try rewriting to use STM. (And thank you for the quick fixes!)

**Comment by mitchellwrosen** [comment]
I've amended the test and opened #15, but it's going crazy on the `fix-13` branch. Logs are an infinite loop that looks like:

```
ThreadId 37458: Processing the finalizer exceptions
ThreadId 37458: Finishing
ThreadId 37462: Forking from ThreadId 37461
ThreadId 37462: []
ThreadId 37462: Finalizing
ThreadId 37462: Waiting at registration gate
ThreadId 37462: Deleting itself from the registry
ThreadId 37462: Processing the exceptions
ThreadId 37462: Processing the computation exception
ThreadId 37462: Processing the slaves dying exceptions
ThreadId 37462: Processing the finalizer exceptions
ThreadId 37462: Finishing
ThreadId 37463: Forking from ThreadId 37461
ThreadId 37463: []
ThreadId 37463: Finalizing
ThreadId 37463: Waiting at registration gate
ThreadId 37466: Forking from ThreadId 8
ThreadId 37463: Deleting itself from the registry
ThreadId 37463: Processing the exceptions
ThreadId 37463: Processing the computation exception
ThreadId 37463: Processing the slaves dying exceptions
ThreadId 37463: Processing the finalizer exceptions
```

**Comment by mitchellwrosen** [comment]
I suspect my hacky `threadDelay` is too short.

**Comment by mitchellwrosen** [comment]
Ah sorry, forget that last comment, I was reading code on the wrong branch.

**Comment by mitchellwrosen** [comment]
Sorry @nikita-volkov for the spam, the logs are because I was running all of the thousands of other tests. Your branch has fixed the issue. Yay!

**Comment by nikita-volkov** [comment]
Yes, it did fix this issue. But with this fix #11 is broken now :)

> And thank you for the quick fixes!

Thanks for your contributions and discoveries! It's great that we have so many tests now. Lets us be more certain about what we do.

**Comment by nikita-volkov** [comment]
Alright! All current issues are fixed now. The `1.0.2.7` release has it all covered!

**Comment by mitchellwrosen** [comment]
Awesome! I'll check it out.
