### ISSUE TITLE
Revert recent change to use `forkIOWithUnmask`

### ISSUE THREAD

**Issue by mitchellwrosen** [nikita-volkov/slave-thread#16]
Hi Nikita, sorry about this, but I think my recent patch to swap out `forkIO` for `forkIOWithUnmask` was not quite correct.

I believe `forkIOWithUnmask` is useful for IO computations that happen to spawn helper threads, and want to be usable in any context (including during resource acquisition, i.e. underneath a mask).

However, when the IO action itself _is_ a fork, well, there's no surprise fork that might happen underneath :)

If `fork` in this library uses `forkIOWithUnmask` under the hood, then this pattern becomes impossible:

```haskell
mask $ \unmask ->
  fork (unmask computation)
```

because an exception can sneak in right here:

```haskell
mask $ \unmask ->
  fork (    unmask computation)
        ^^^^
```

I felt this pain recently when writing a test, which had to use an MVar to synchronize with another thread since it could not be started with exceptions masked.

Now, what I'm not 100% sure of is if the above pattern is useful in the context of `slave-thread`, since I believe this general style of threaded programming encourages robust error handling facilities, and does _not_ necessarily require or encourage precise and careful exception handling techniques - just let it crash.

Anyways, I think the right move here is to revert the change, and possibly/probably offer a second version of `fork` called `forkWithUnmask`, just like `base` and `async` do. What are your thoughts? Btw, I'm happy to provide a PR.

**Comment by nikita-volkov** [comment]
> Anyways, I think the right move here is to revert the change, and possibly/probably offer a second version of fork called forkWithUnmask, just like base and async do. What are your thoughts? Btw, I'm happy to provide a PR.

Sure!
